@startuml
!include style.puml
skinparam arrowThickness 1.2
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueStudentList
AddressBook *-right-> "1" UniqueTimeSlotList
AddressBook *-left-> "1" UniqueGradeList
UniqueTimeSlotList -[hidden]down- UniqueStudentList
UniqueGradeList -[hidden]down- UniqueStudentList

UniqueTimeSlotList -right-> "*" Timeslot
UniqueGradeList -right-> "*" Grade
UniqueStudentList -right-> Student

Student -up-> "*" Timeslot
Student -up-> "*" Grade

Student *--> Name
Student *--> Phone
Student *--> Email
Student *--> Address
@enduml
